; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\Goldaev\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.cpp"
